# Generated by Django 3.2 on 2022-09-22 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Montact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chat', models.CharField(default='null', max_length=200)),
                ('Intent', models.CharField(default='null', max_length=200)),
                ('Sender_ID', models.CharField(default='10000', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Utterance', models.CharField(default='null', max_length=200)),
                ('Entities', models.CharField(default='null', max_length=500)),
                ('Traits', models.CharField(default='null', max_length=500)),
                ('Details', models.JSONField()),
                ('Shrug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.montact')),
            ],
        ),
    ]
